<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LSports.Core.Database.OrmLite.Extensions" Version="4.0.0.126" />
    <PackageReference Include="LSports.Legacy.Common.Entities" Version="3.1.1.184" />
    <PackageReference Include="LSports.Legacy.Repository.Generic" Version="3.1.0.42" />
    <PackageReference Include="LSports.Framework.Repository.Extensions" Version="3.1.0.15" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="7.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LSports.DataMapping.Abstractions\LSports.DataMapping.Abstractions.csproj" />
  </ItemGroup>

</Project>
